*** Starting uWSGI 2.0.18 (64bit) on [Tue May  7 21:05:09 2019] ***
compiled with version: 7.3.0 on 17 April 2019 10:10:40
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: xt
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/xuetianyyy/.virtualenvs/xt_py3/dailyfresh
writing pidfile to uwsgi.pid
detected binary path: /home/xuetianyyy/.local/bin/uwsgi
chdir() to /home/xuetianyyy/.virtualenvs/xt_py3/dailyfresh
your processes number limit is 7453
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
Python main interpreter initialized at 0x55ea29317c50
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./dailyfresh/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/xuetianyyy/.local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/xuetianyyy/.local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/xuetianyyy/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/xuetianyyy/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/xuetianyyy/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./dailyfresh/settings.py", line 208, in <module>
    import djcelery
ModuleNotFoundError: No module named 'djcelery'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30738)
spawned uWSGI worker 1 (pid: 30746, cores: 2)
spawned uWSGI worker 2 (pid: 30747, cores: 2)
spawned uWSGI worker 3 (pid: 30748, cores: 2)
spawned uWSGI worker 4 (pid: 30749, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 30747|app: -1|req: -1/1] 192.168.171.1 () {40 vars in 698 bytes} [Tue May  7 21:14:11 2019] GET /admin => generated 21 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 30746|app: -1|req: -1/2] 192.168.171.1 () {40 vars in 698 bytes} [Tue May  7 21:16:20 2019] GET /admin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
